name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux-Release",
            os: ubuntu-latest,
            cmake_opts: "-DCMAKE_SYSTEM_NAME=Android \
              -DALSOFT_REQUIRE_RTKIT=ON \
              -DALSOFT_REQUIRE_ALSA=ON \
              -DALSOFT_REQUIRE_OSS=ON \
              -DALSOFT_REQUIRE_PORTAUDIO=ON \
              -DALSOFT_REQUIRE_PULSEAUDIO=ON \
              -DALSOFT_REQUIRE_JACK=ON \
              -DALSOFT_REQUIRE_PIPEWIRE=ON \
              -DALSOFT_TESTS=ON",
            deps_cmdline: "curl -o ~/android-ndk.zip https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
              unzip -q ~/android-ndk.zip -d ~ \
             'android-ndk-r21/build/cmake/*' \
             'android-ndk-r21/build/core/toolchains/arm-linux-androideabi-*/*' \
             'android-ndk-r21/platforms/android-16/arch-arm/*' \
             'android-ndk-r21/source.properties' \
             'android-ndk-r21/sources/android/support/include/*' \
             'android-ndk-r21/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/*' \
             'android-ndk-r21/sources/cxx-stl/llvm-libc++/include/*' \
             'android-ndk-r21/sysroot/*' \
             'android-ndk-r21/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/*' \
             'android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/*'
             export OBOE_LOC=~/oboe
             git clone --depth 1 -b 1.3-stable https://github.com/google/oboe "$OBOE_LOC"",
            build_type: "Release"
          }
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}
