name: CMake Android build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build OpenAL use cmake
      run: bash ci_build.bash

    # - name: Upload build output
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: openal
    #     path: lib
