name: Android NDK build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build OpenAL use ndk-build
      run: |
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
        $ANDROID_NDK_HOME/ndk-build

    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: openal
        path: lib
